{% set name = "tplot" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tplot-{{ version }}.tar.gz
  sha256: dab6eab07321b1a62fa6fbb73fdcde1f01e7570dfaf5bd78d4abc55d9b9b8b3f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry >=0.12
    - pip
    - python >=3.6.2
  run:
    - backports.cached-property >=1.0.1,<2.0.0
    - colorama >=0.4.3
    - importlib-metadata >=3.1.0
    - numpy >=1.11
    - python >=3.6.2
    - termcolor >=1.1.0

test:
  imports:
    - tplot
  commands:
    - pip list | grep -E '{{ name }}\s+{{ version }}'
  requires:
    - pip

about:
  home: https://github.com/JeroenDelcour/tplot
  doc_url: https://tplot.readthedocs.io/en/latest/
  summary: Create text-based graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
