{% set name = "tplot" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tplot-{{ version }}.tar.gz
  sha256: f20ff64dafbf799da7726fca44dd09f66747d12c57527a21f94c150aa6d7e70a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry >=0.12
    - pip
    - python >=3.6.2
  run:
    - colorama >=0.4.3
    - importlib-metadata >=3.1.0
    - numpy >=1.11
    - python >=3.6.2
    - termcolor >=1.1.0

test:
  imports:
    - tplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JeroenDelcour/tplot
  doc_url: https://tplot.readthedocs.io/en/latest/
  summary: Create text-based graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
